// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bahlraqdmdtvrxixfnxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhaGxyYXFkbWR0dnJ4aXhmbnhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODM3ODYsImV4cCI6MjA2MjQ1OTc4Nn0._4aX8a400CmlpdFmX47ItPlgW4W3yPMYeSUgT6DTqL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);